name: genimages
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  injectable: ^2.5.1
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  shimmer: ^3.0.0
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  
flutter:
  assets:
    - .env
  uses-material-design: true
